// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGDopwB2NwMvZm1YatSKuehFdeQaUTbkI',
    appId: '1:714916749601:web:13ddb534a5b1afc00c9e60',
    messagingSenderId: '714916749601',
    projectId: 'diletta-web-base',
    authDomain: 'diletta-web-base.firebaseapp.com',
    storageBucket: 'diletta-web-base.appspot.com',
    measurementId: 'G-F8NCRRYTH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcZSs4tF1UFy0DSnbwWgapc_elSYxDL9Q',
    appId: '1:714916749601:android:5d397463655279620c9e60',
    messagingSenderId: '714916749601',
    projectId: 'diletta-web-base',
    storageBucket: 'diletta-web-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPmfrDwfQs-AflFdsf4nGwxUV-HPM_FQg',
    appId: '1:714916749601:ios:ee33db6d62e80dfb0c9e60',
    messagingSenderId: '714916749601',
    projectId: 'diletta-web-base',
    storageBucket: 'diletta-web-base.appspot.com',
    iosClientId:
        '714916749601-1qmcpk2351e7k2ir954en0rtgib8jm91.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.web-base',
  );
}
